WITH VT AS (
    SELECT CART_ID
    FROM CART_PRODUCTS
    WHERE NAME = 'Yogurt'
)
SELECT DISTINCT VT.CART_ID
FROM VT
INNER JOIN CART_PRODUCTS CP
ON VT.CART_ID = CP.CART_ID
AND CP.CART_ID = 'Milk'
ORDER BY ID